apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koito-data
  namespace: koito
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
