---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: koito-secrets
  namespace: koito
spec:
  encryptedData:
    KOITO_DEFAULT_PASSWORD: AgBEaU8hjIllU/Ba7yiQuQUtrN6f6gqQxDjp26IIULJYwsiJPZKT7Slbv2UJQtRM/1gnvBRkS7nGxr+i4bY+l+/2YkocQS23Lv6AFi3gvDPCfZPrzKqijeQgGNKBXvUb44+G3kWYJbwnI5rubqokdlkESKWuy3AXw4grXzLcS2dSUeFNfacVm0TXiEPzn2YWVIZkajSvimKtyvUhPQ7XR6yaMeFdIQHNfAjR6LulDBSo6IKSi/+2IW0B113NJz9tvd028T5PZ+KLROQsYKqZ/cZdGR2GARadWDJe9Yild/Q4h8kt5YcmYc4uDjZDq8PLhn3EiHPnfgqKXpxGUn/0h1DpIQIR/EKhiJSXDLi/GNau5CmdhGj0p6oiebJPl7JEI1Nxz8DqUIwKWCS38jazhn/iR+jnSQf+P1eBJHJj5zr8o+PJPxg5lEbOGAHhXYczCMcjmh4zXpNfWwqt7v/sxYIoGWwDvgOPsyn5jg+iyTEZkI4zeMNgyjcU00bfJ0D8/Bv4mCiHsLl1LXIxrNGelBLt16jEeJk5S1vuecWyliF0kBGR/55UQvD8lhqFBm6FaJQmQZ3Ab8rEbI8++rRFRw8NrjhqY/85h6eKjbNW/SVdLHeBzHL8mBlSjvzyWCQR22YBsyAx2tZKtxdmvamGZIkyjTICBYDKgfDqyUvKW3E8AzCNZzS6UchtkpluHe13b0CFMwfyRWmpda6+zGo363kvKEFS3yx6/3g=
    KOITO_DEFAULT_USERNAME: AgA4aYb9YhJC5RIkQePRFg1Ho7SHuIUt7fdIzJ7YdNdbOblspy57s2UUQO12crPVbGP2kaErG+41APahOQkZmsP0x7ZPVjF+0xRb+Y7PbTkqUVtdZqWuoCWSgU/sd8HuWG8qYUlERzDeqPtRxWsJB2WZw2O347B6DEX3pdPvPxmfwmJbc985o8Y+XG/L/iP09VYuyzbsZTQVpg1dFjK8Hpr5aBwNVJoAOV2FBwUiBUtjINgI6QmhGxEbm1lrNqHHjDTybP00aPxLMyaip5KoW6U8wVdP+crZ39p+TJBtNcG1jxy6zag5idAZUMa1/tXgwDH0ubeZ5npNgHS4xgWdA85C85PTm1CqeprFyE8rVtkAuYb+oK1/Amft1lxoNiiJm26xWlJyo7iUmysy/OtO5CiErVq8lYonZl7Df9ZNO+gZFRb50g4G6EbbwceiggbvNrjz00pJqOVz3XNe94SCJk0pkh0XZhHgNKoKR+00UKycRAmaIt9OZIstZZLEShvsQ98gWPbKXo3rxucwJ3FGu806FnpDdwtbdg4IDrxcaOynDqB8WCViGpbMd5QPlnW0T2YY2rgpgSa1+7a1IL2KEva7tIlDSgfIhJXZS8NYPxKKV5SggkzJSBVPMa2t4B89GaRQtWeIAfXagy8iME1ELVPmC+vqG+6excZSqZQ10jFX+zYV3B/qjPyHCKdP4MdqMyhwzsOfjQ==
  template:
    metadata:
      creationTimestamp: null
      name: koito-secrets
      namespace: koito
