apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - tlsstore.yaml
  # Certificate re-added in Phase B once cert-manager CRDs are installed
  # - certificate.yaml
  - ./middlewares
