apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 1h
  chart:
    spec:
      chart: forgejo
      version: "17.1.4"
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: flux-system
  values:
    image:
      rootless: true

    gitea:
      admin:
        username: forgejo-admin
        password: admin123
        email: admin@forgejo.local
      config:
        server:
          DOMAIN: fgit.watchtoken.org
          ROOT_URL: https://fgit.watchtoken.org
          SSH_DOMAIN: ssh.watchtoken.org
          SSH_PORT: 22
        database:
          DB_TYPE: postgres
          HOST: 192.168.254.104:5432
          NAME: forgejo
          USER: forgejo
          PASSWD_URI: file:/secrets/db-passwd
          SSL_MODE: disable
        metrics:
          ENABLED: "true"

    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: forgejo.local
          paths:
            - path: /
              pathType: Prefix
              port: http

    service:
      http:
        type: ClusterIP
        port: 3000
      ssh:
        type: NodePort
        port: 22
        nodePort: 30022

    persistence:
      enabled: true
      create: true
      size: 10Gi
      storageClass: local-path

    extraVolumes:
      - name: forgejo-db-passwd
        secret:
          secretName: forgejo-db-passwd

    extraContainerVolumeMounts:
      - name: forgejo-db-passwd
        mountPath: /secrets/db-passwd
        subPath: DB_PASSWD
        readOnly: true

    extraInitVolumeMounts:
      - name: forgejo-db-passwd
        mountPath: /secrets/db-passwd
        subPath: DB_PASSWD
        readOnly: true

    redis:
      enabled: false

    redis-cluster:
      enabled: false
