---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-db-passwd
  namespace: forgejo
spec:
  encryptedData:
    DB_PASSWD: AgDhzeMNRsimudXkPCYUTKDI5AH8FtKxTS/hl8tbxaTXiHg5b7M+3aU4CDCopivS+ljNOWkG1xufy4oyCGQzNLKdGFJmvKd5SCCyhxjhkeUi4IUjh2KBi3jCAF6OeJivGhFNd74Z8kZJh+93uI8gnFoldpZ/HgLAYI14Dn7WxBKWCous5NT7wG4rPL1vjMWadiknbCqL4nfKFHpig6s7g/NR2rOyFcLX6t34q3BR5+NRONPT1vevL2WcXTsOaLgbVWPMZsF6T5IFHI+HErTEO9Qo18lh0AmGYzZq5mvEghl4FcCdpKQUtuomQKELrpdDYgFyIm2UyHhNMhYUjJDQwUPK8Cly2aE9BToRvHDoIpwMRfjWContmVCYCwr8GuAO0AJkRXq/WwunkN0Jeb07D6RzENsOMtKk1ewHQJW0zSKm0WBElm8b0IyRDr+Vp/eBJ5gxWJCQDnwkndaLfLsPq2dakgGbWhhhOpW89c5gRtduL5ZrxQYiHGdwn99Q41JjrgryDRVPTKcrPA72NqyBjgjMtP/aprelU6eAmL9BdRLYymLXf0KizNSdl60hn+syonAVE4mq2td/c09Sn5gcdUsPeRwyGRU5PdLT4PO6FELzVMzmq53VKmyAb/pOmEUAzWvD/o6XfoBvOJqUaGUSdYn5Q9pFdy1b2Kum3E/fCwm1LlrccnIZxYxJBLU3w1rwQ2TZEynhLnP7Nik/1rhbAXLK20bAwfJHPKJ+uZ3jeIppCH3y+qOnVvz977wpQV9fv90=
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-db-passwd
      namespace: forgejo
    type: Opaque
