---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgALQCx2op7HhZKVJKsGHN/JDt2rZxaBMUwHEc8d9KqFNkDZWYDHpqWOHfPeAXbIjporbvAXqUEUISBFH+GK3fUcrU9Nu8/nMpB4YU0AQ9M2kHybOXtnuUiExgZLg1h4J+PC+eItO6rMjaLo1ZdoFI4rJ2jZ0f9UZ3twIcDNWNAxnB2qRRw+3zfTUGc9jBCjwAOij3HJTu+mpzwMmHn+QNGFX1elqARO0UJfoWAJLA3yLkru6q4FPad/SifP3c/ZGkW9c+Jn3SmIY0nefxwLuzJn1OI7hs0rWZwVnGxacvf2a7mlL8JUwr9LOr5DU4UJnErpFt9KrmXgc3zmPDwP7TcgNSkvRPqt43P0p4dZRY+3OzmLinGVg5VHDdZDzhyzpr6djgQxueLQboduU2j5Kn3uvI7AZTGXhKBMjR6hdzZF02r1A6fQncTa7J41ZPaBG4seE7+HJ93+5Q+6UmPAa9KRD14B04wYafUM/EcwhDySVjYMaNcVOMKTxVWiC4Gw5lyHd2mXl4u2Ie6psHxOaY7rV3+apsedNdVJVx+n6Km+1Q7jeu+BPB3xAvvUJ6dK1FX0PlN8/sroZmiC9JgFsqAS1kHchfOGcbBYw287sN/UUaUgGwjLKH6z6BohfscUJ9EJvBsxSoc0Z7+hNDgq8oCP6GLGM4SEK7plCTndYfuhCglzLNXs+IzItrFrt4UjnUW1W+BdmH8NngWnhXpOhDGtM8T7lo9CLfL0jd2MAqHMjBAonRH9f/ztUjJxIjaMk2Qj55SiwDC/4RKFRPglEenx9ydlLdwb48Xwbk+2uO9MOcZUgvHIGIqJ/gvDkbWncOCDXph4JL41WELov3ti8/K/MZTtvwgvIhL8+/+9xpnO1YBH3v7XBkJpSvzlrBhoK04qcS6T7JQ5kpYbl01YI7HtY9W1UpEEphge/LRbZnlYJj2iRPPrumSDQwBVae1/SXGGL/FTzY7jTnRpqRutvqGoekudu6vj/AXCl9sI9H/aIIGIPjJKiT4JqBV/nUqu/hIoNaf/TMWrfGQumqrdr7FojQ9b8/qEEwLB+nl0aK+joXNHjbCkbZ5BLzoeOM/76yPAMLQlCC8+71CfVoVugT0QZVSXglZKIf5nMmFL3FIa43vlfihElw/Kh0ireMrTSDxitAa9GQ==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config
      namespace: monitoring
    type: Opaque
