---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBUexF8VsQO5U+kP1JeaGo6y1gprUEbLyGybrT0Bstv90agT4Gi7yh7c9REVgkoGjUgJLHSqO0pdtkat9GldsvPL9HEjX0Ad6rERho7eqY8HSTXp9Vyv7RP5ja+uSGvJ0XPinT70j7szYPllYHlcfb52uIXqqU+RiwRgEeNm4XjH8KfKLCWLy63Bxp4FYvHSbdD/7FCWnp1v31ID3nsBPWIR+H+TsTWOiTOSbOsMgA8pPHFyNQ5l2bPUhPxzP6uC1rDE4RHZqruZ6vWonTl0bex3uQRWrMoevcmBViXGvMz74tNpuByyD4CDc0JaREQxI6IxcvTJx2mZfhGGU1hS16vTI7e1K5z1wyVG/E2GEsoKSEaCPMSledbp+3MraUCnIYjRIAhZqnS97CCjZJR1aLWaq8P6vKX5CVRacNOhJNXu2Kp5qoH08FCPSZNdNMyElPdS8sNYWTiPSDyNwy03FyONRABwYTiLKJ4KJIxJpIoTg3m9ZjFksOqmkDPx5z6BEYeHW98jcf4sRG1gJ7qgSx2k8pAePOt6VEAKdh8ufbPXFdiN1Wsh+6nufUZIDkYmbp+4xKqmQMxKXV32Auhd+CsB6PbYYpKquPpjQVg0x0bBXpbmRIluuF/mjyCTtuySDo6u+0rNnIIythlut61KWjlZuer3SPoGEpeHRLoes2GuqrlBWGuxSeFISZKQB66aVX8jNpkGkluVNYqyyknSNfGjIsBMbAG05k=
    admin-user: AgB9ylMWCl9Hi4SgkKjM+50ZJ8h6S2A06p5Q48Awe/u+E5mQ1utE+/XiOOfqZu636lxOQ7k1C64RWzTmAe1y5PYnZ6tWkFw9Jmy+D+ARSpC9ulJPpsQ9ipbmZSRV8ITa/jRucZ/i+SMx6mVBCCILoH9sNZ2J8yyN6ojxCrEZX5/P7Cs/t7WAO5vxXdXQmidvXa0LsstTgDj3fhek8wUzYblO879+Oy1/DGw24vn3NOA0i2tCATY8dwuMZtPL8dFQQiSOwi+ngaC5tVFn0+ySFJoL/pPyzOSvkgTrrLLgKx8/PNzjPZVJHgnr2yRNRitb0wk3qlneTmS+w8WmA5U/t5R5aKjXG63k2CKgheavwul+xxGlNJyG/9gbNYkHzP6JXGGeSq/1y81dhhJq+GquoHn9qfgu/VUD0OlmbU+qfAfhPajnE665w5tmNG6O++JiVI+4F+L40Jl8cYA7rWVsMSYu9jlsAynRqiTzb7uWG1KJ4oFr9wglSnur/zPh+MardPtPzo3w16WlF+EIno5upZKH7G/oMP0SCBFihSG4bLHyoChLL5Aq8KH9UWXCiAx5RoIKtuCFh+yKOAftZRjGMy/o+2Oi4MAHhvH++4lrFyKik9hF3yxcJwnpLK1AM4GN16lbApV9P5rFY8a7LuUUyyoYGdziD8Pny/djtPEIQQI0EE2smhHxSsFPUbcz+XcHTCeWRuAboA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
