---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgCxpqnNvsr4/LHlFvs3SJOrMZ6AdRCc3GnCr4dJThrxkjKr8uESAWuoRj6vsYWDYmeNVmbljBWJ7EKLrT2z3Zx6EWxMn3hyCszRBGzLtT/Cw30Xm5KgA6S3QIsDbsvTr9gXfPjLVa6kFvls48/YiYOv9190wslHchm2XWqjmnrR8B8rAH/HXMu8R+8YJFlXyF81SUZCV1J0PfiOxuo8nn/lcmJFpVxDo57RP/YXCAcHOtJqHXgRUbRqloeDDxH41xYqc0S7lB5S6031BSj1+rxHsttC/OFFuxgi4RsQhdz60WVWhqXwDRuOFL6CwCMhMRCkzSZinCGxOhbsBo4g74Pq9zV7e77m55DcKtQDdFTP/ZAr7vuNsRtEKCXEVdfEvwUbkmEvZMZ7Ef+DEcq8q5rm1W7XxpIvZfjIkyVN/YezFIhU+E/ehucxvqL2a0M7I/0xEgEZswULyliMxLBQQHJ7jHIcuhrg1gr266Zgzc+EDSyqZK2aUPALOYLTFcNGmDzjExHQD2dU3zasy3LALUXJN3H9ugWs5oFOiY9hieoqBhoV9sQPp0IOdvCSbjXTEDkbwqZM+b8FvdznVragVU3JzU/yimk1rASe15Mz76w15N7hHadgI1jI+xiAlUxsa0a6Cezqr+0EJ/dLU25WCmMF9ASLqryUmeQAOT6aWgn3ji/M/nui4gGA7lSW+bHlvmO+eh49k2RBogiS6Q+/DFxMXndIvZTNPzO+ROnZ/JvNqeqzUuFvWUkepsY7x8R6bbpxH4LtYAbzKGz5z9J2C9MLWD6kFFL+0YtEy1oX0TkoqrnCUVCkLJLzzY1H6BVtmMNPAjRm4HJb8Y7SZCa4/YgCCt/6TO3PjEsAtY5Wy93lOCaSWeeErJMCickvU5AJA8t2hPCf/x7H73vy37XAvzWqgzYh5jOS7hMCo4r+TIWvsz9Ryw/w4xwT57GnffGrKr9P2FQVsjjGvAx44iQVtGOHmwnvAz4F4Cdez6LH23/p/8uR/p1B1rYaGt3JpufrxDRJCjxadf84vfk7ktMyEtDlt0BsvDj0rav3uftpfX0YYdni9BOksVQCGmaw9T9SLYlWDaLjG7BH/77GJqrmgGM/gLepBMnafs7TTe46jO74ZasL+EXLM0gkqxLEAGsqkS1C
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config
      namespace: monitoring
    type: Opaque
