apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service.yaml
  - endpointslice.yaml
  - issuer.yaml
  - certificate.yaml
  - sealedsecret-pve-ca.yaml
  - serverstransport.yaml
  - ingressroute-http.yaml
  - ingressroute.yaml
