---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-alacaba-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBnxoMCAAaCMznNPvuflvKvbcoLnMAsnRyMFiWg6SjbEEeUznbToGUsQ1UEhQ4KvGbmnH4/YkpaWc00JdxEIWDcn5XT02wlujIWNvWeaOKtI0OCkvyyEdkQUtSPkSl/1BLflpfnqcAktDcecHVmwYzU7af/aDuN31AXSKre4EsELibrjjn2/ZTHm68Zo8gi7GSYaVaXhEnz0QjDemSC2OnXOOgEaag0c0Qu/94GNRgBGZL1uDAVGc9aRqgBbmG/aUZ0UIUAyVki3ILRnMPrWJ5NF/N5lN/6RB7Xk+2MaPY9QvTef+2Z6SC64If1wXNC2b9g+Quw6nYb1HQeN5OEaQgaMWIkzfkBrjAg3nfrFI/chloYX82IpLEQVzUMokikDdshEsmLJngZj84RLEQbB2tU9l7e/OAM2qmTHAO1z3R0YV04My4iaa08tX4y6U86kVMiShyK3DQblMVTBzr0MGR5KYVp7N0yZBE2UgalgmL566hyE8sBsiWKJIm0Z7WM7Tf5sMXxe1DgCQ3lUtDvKQOp480itM66u/XgkLkoV3Ykk5WsVxiVtQY5YmeRX36XrulFgRaVLDhjnpVsNIRD7RjnaX+z9kwBuz6sbBFpDIgQIeBN6KZdl0N1xvH0l8gfDdFmhAt4lTvdyeQztd3Kh7T4XCIVIo2MmiPYC0a8Zv6XbsEW58ryOoq7kgAxr+agWgo=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-alacaba-api-token
      namespace: cert-manager
    type: Opaque
