---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBxQMyRyDkZoiwRqkKs6GFn/g/AZ9uUC8m2jRYbrdnrurZIGvcFwC4s/QbSagFyTiaYauupWGtvtw+o+gxddCeS2ntZQv/77n+cE094nDW1ReCH2oJ42OK7mvVhfMMlqXakKE4k6LdPpISg7z5eRv43ys/sre9yuHwLpGtDEa+RZb4MYkl6DyeQyWWPFMKBeNlphNjQ2pyXSIeeFEHP9DH5ZgOHJSsLbIc/qXXIUAgu5Eo6H5SV1aw/BU6edGA0BSud9gM6Qq3ZWANJovvDqn0xOgtp3F/cQrirPlNCIVjajS/As+YvjI10+ExlR8CbZw5VEZlsravNqrH6vlr1WJdvbdZwqZY0KfVgrrfVXNt+QNhqykFqfUJGoV5+kOUbaL1G9j56Jx0gVCq6wS0YAr766FYWwkGqZYsY8dzREQV9MNUM9qK0OUUNDd1C/gZRwNFy/IrP8B4uzDilj/aAD6A9YR8wM7vpk82bRg5iKhIbxAAMZdxF+9kIuCprteSqeWYhStp8u2Gpiv7wLYvjFmY/3eyxRkd1TfYff3AotPJGzpiqCMcvkqmF/PLsTqKs2IYr3K6if409llrI/fjw2Kxtbep7Lfigguhe09P8ACFxiEAVArKCINh/nnvr611rU3rVRsO4RU/fj8il4NJ9pgCKvBxs6+JncqY3zReSqGF5c+6t3BqgOlxM0W51SEC8hTWkNCFK2fyg0EbWSAIpVgo8UUaVOrVJZA3IWksAl/buVTdWAraQRxdDuAjY0M5exBqIVMImsg==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
