---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB9HpSADbjYpAo0x9wxZbzg5CeuDi1Lx13vv4SMOGJ0sAMlVpKugkMPifAKQnToBIvDmxAm0+55ETGR3uLXlfLS1OTZYUZYlvUqvVdRsQRvBRTn3Mq8v8var85QSocyjXegYd1ohEkmwyqakYFsAmRgN6woVW7ZQ4MQM25nD9rwIh3OdfROcvAcfUvQ5hS4lfspQITnBIvPcksrtSX9h5QbjLu6p7RIK/oN0cAPjK2aKSCprDecr23X7rCmULecZtbayG9aanUN37pNhDpiNREY3q/nJznugdpHyAOnCs8ShFKsHPcyWkgqSFKYJ4Zq24olKkaYgz/kfMwVWIAtOWfPEltQqpebwJcLS3QcLFe441pKEhSaqsJ5MJDLkycq0pXLdgG5vDLfXoIptywBhLWeOipswgBSJYWBSei+3ut38bzzkX60ISRJQqhsd2ykn3FntCC6qUdmyc+i59t7Ztqv81hs//qnLPa01XXX/H13VlUTIczBXov5pLVSvT2xVzIIDgdZmNUdh16ttrahtVvRabJxFQ3cPu3sCWggiurlaCqpN4IGs1CfGLWWN8MrO3jc1n6tb0KvM3263IG0F4y+2wHcWQMsqi+zKq5L+2kSlu8XVDyRofuJXQsCTxrWba2y+Ejjzfa8ridicX4XCFVTO73fowG+BfRiX/zSPjN+bSDJgtg6JclKb9xvuaICyazBzpA92zxBLUsRUR39ogjH94iuPwiLAXPw+SLHOnWvkK4vMaEGHUetQ8F5wBotFppQ/VSQKg==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
