---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBz4xyB4JGYwLmVfQIhGrWcUE9OItSkN3IJmg1q5ul/yYBQOXjKwJMqHB4OC4aX9ggyAZGZXdb6ObG/DVwY3YloAYqb9Bm/AtQ/fCDQ2XeszxbMaGcy31sXpOsbtmSwtyLF30RYN6LbJNPNYKeNJkntvhU0EDXE46pBx7szPjnZzGCElaKWz4PN2BSpB4ae/gSiW83RBNtVCvp4SYX9DUo3MHpTA1eIgsLt3mDJbkT8ZPR8haoRGsu0j+inTpY9UEjDIz7wgnQeidwHWacJwMvchRGHP+iZUM/MeclpjxyO94/rzvOT5DawRS9bd+p49jzugBHMA4A5qH+y5DUhzLAua7N8GfdJaFiYgRRoWTaDCrlEUJgYNZfcfH+4R5YZ4EKkor1Fe+vZ+e3vA8aaxpQUq+67j8uDlUFUCsRqOlkGnayH7sHu6waCaiP1zl+48R22OLmTul0S3YowyCW1fW0nz82IkdR17E1y5FhoyYsUJ9kqh9IL9+3xP3IbE9uMoCtIW0JKYIgwrUoQXybzlIO2OMM1j/8V2HohxDh/Gj3CKgMqL4xUfOA5lGCHpaFpVMH2H0d50JPDK9mChPzmC8MlFYktJv+HSmLE+iUm0wpjvL2E6zX8jusXNthARl39hGjDMke7N6mZNToEkcN7YTwnUA9DSCYnfyFjxl5L2W3MS8D+JUVqNfmLffHueUuJyP8pXn2J4fbHRFR46obG5Ji2coHC0KiG5MJwSivb/BuBKo2n7pn9Dj+5LfUFLMrpJIiQDTWUuw==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
