---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-alacaba-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCtbhSmhBnbnPTTdIRpsxrA/+J4XdlWzt1mXW4d6WPt/gGDFN2WAqTnditq3MTqzbkeC6gw6owg3Ykh837+ZS1saHYYcxTulCa2L4Aw1+SNDI621wXEpG2ECnLDkw2PiN8WHEp943DhueD9uM8+LM2bsNSb1AHpeJl+DJ4P+fRfBKHOhSZ04GDX08q0ay+MMB3hq5I1iXKXxeLlHNKkrT78f7Yfi1hs6v2B93kqFknEV/g9jaavlydq2McYRcl0ZhyR2+1FMlZ5v9MqcRtq4Z4Hng5MJ51ZnHBqMQYYgEoKF2BGxK1sqvvQlh01kKmMy9MN/91P0lJTkgKA7FocXlJo8vXQc0t/maZ7PVNawA2NthL4ysiDhk+ndpYvT35OXFlIbCrpTo0TrEl7/cp7JbP4Ol1ORHArIaI5+JmR2fiMavrnM3HzPcxJ7/MBn173EX/2Z32E3LFqZaCTu6WDJER6aIf3KEu5QW3x7q2c5LGhlEaa4VOs4zKAhswYuF8o8VFl0a1P1AjWIjkImsKLLl/sEQXeQHpSa1Emob3XU+WJzC+sS359Al6fjWiXgRWoqu3a5onphlAIqz/B0G9/SNnc3LYn7bpldb0LSY2wBxYo9hkaqPgOPahn5ta43+zrco8aES04lyPWO2At/4gGHjDIs1owjddGlqpVYftB5RmH2GEqLtAQOYdQgffrKqTd2QCYMLVKxwY7C8dZfmy24IOs6GRzZJeVVBL1BA/JB3Kb2M9pXuiNpA/QnIr3soAs5G18GtgQNA==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-alacaba-api-token
      namespace: cert-manager
    type: Opaque
