---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-alacaba-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBZvoI9NMNw+HxD+4VUZdK073RVPjADidaaDO+8DxpyBTHX5sbUOV5jlz8vgw3aqmUhmxIfAd4RSfCS18cyiWVA1Xmzou1Ffjev4Ii5uz2wdmR68bFZGDKidF9cCeARtdUABymOIBJs2K36jg9sjTdPfg49PyWUQhhH63h9jmWdQ9d/AhQM0N6hGfHc0POBKT5tStI6C0OJjPjfIqmert41bjoZ/wj7yqIBZM+vhhZl+Fcn7fI4QRL/euceryWtDAzY9LF8lTNyWShFV0Klg4Z7/NDMa4SDCbcqFQEh8F9Z7qP+kbr6U7xfhb+heKaEzDWoxhpGAiwctpmcj8ELlJgP4GWGeZ1/DveO+17TLgbul7ooZBu+pc7+yKWmhA7t4lcha1PZr/+ZasVAU6fy2I3q/PLsd+9XIhwqrm8sURAacDd9A4AcfvBQCY666VU8JJv8smWhVkL20CnRk/mUyLOsoBA65l61qM/Td49LGAGxeh48EXdibXoDhoZ/HLxodEiu7g4qmpO+nKQCIoxBAbS4fDr1Q8Lou1aYAc879rr1Y1nkn8tRuilOG/9S74QYiWmD8QbGT15zz6wMVweZW9s4l78y6g/Qo593l3kofv5eIXajvLCaNNyDZA1Wy5OzV2QYFjfVnPK7W228koLoidP7qI0Wi2olfHnSuC/JNkLIX4cT/38ERnrrUoqJbBSI8DFIdakqtqrhC7o9W5XAMNvNKZXelElfVMW9aKaXwYkVdn04aEycrrF7g8CNiiVWo3RD9utsTg==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-alacaba-api-token
      namespace: cert-manager
    type: Opaque
