apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windshift-data
  namespace: windshift
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
