---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: windshift-secret
  namespace: windshift
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBVf3LTNmY+hdHu1RfweElpwwIpKGnK27YtM9J/sZ94T4YcgNF3hbF+jqrUuETqYEOKdaiBgzow3ASJTKuHm7o/67s+SHULkMEDEvKvV6Rqqcya/5sFmfIy/s2vjYxA9KP4j6khyVgyi1wpX9X/vSo/tXUhg8Shx81vNavMhF0jKM2JQ5i4MDb3wsu7nsIeg3RyKAEtVuGWWckCPz1TGQZFDovI0Nt1AL007i8qUBACLLP43RmJzpZlEwzzOW1b5OUWUfl6LpukhPSQJO17+9diNd/yLM/hWIDDe9lfzj59E7287UFzNhJlTrBJOji66X0jvhfCfLcV1lcgadKfsVECtE2WPz7NzDpwehV6QxQqprrnAfJrfU1+2Wlt4WGR+D07oNyrPppV+QHIQvKNxhziNf9mE0Qp/6WChtdX62fqOO5q0lwAcEYBwoIReLyDf7e+SJqft0b1gbl5XH+HmZkvuUOdTJZWMnmj1eUQzsZCvb0wSO2YNrp0gUBiJx0qQYcH3onQJzhetKK9BPQ9ma70vthrL17GnkSNUWavOHmfU8rW8S1QR3f1mMMBzMtKCm8jH35DgoaPqdqEZnbXziJJOx9szn90toWJUKpI6iExebWaWg7Y9qp4/Nnn7RdS1EaZvYkS+z9g/bk6oURcaE7m661E7WLK7eRVCPCv0bcHkN0h+Xn6NV8OhfrEalMn+ELaBgUseMHb5QPOFxVauvAu7TY4430ZTVXRFdKFwIOca3lTn7lqV1WCee1o9N7pOkckdugbhx+NgT1SCLqCeYuF
    SSO_SECRET: AgAIQs05za/w/i86JeeIKefQVpVpacRKMx4aE7Sv0z9Oopqpd5+wJ+SoQ0AG5woXzogoV0F89Y/0Lk9QBT7F4aBw8GDYXfVM6ys23boMQTdeP5uxUVdLdJ/Zm2Zp35Qri4aKLeXtkIlbBksVBsOIOq7UmzTpqznVGfgBbZQGFE64YggPSMqKcHT9Ows4HUU+LaYdUKkgb4KjILhn1EGzPOCXCQuI5vItPjOVd5n/ngiAG3JuBWKJtaIl6TIzkD05egkPQRnJTwzK/lZBOoI9KsXlfLxtV0iIbf+O+r67GB7ibha8D6mEOH2o2Su9L/Ixg4SP3KTRu3JtT/TREnWfuA0Dx3TAtOXoof+pGrhpE3W2CRiNoezJPctkN8rggcniEZXGfnNefeV/HAeHB2RgnAPffUMssSWrEisiRCp/JE4PlSDYW4RgGbaS7DNb7Sz/rBobYfTkDpD2MZtAD5eNcvfvW8CzmR+qHQpmxt1OucnL7kQ5hWh65g/o8M0OnrvlBCv+4C/+oTJ7tmxRoXiH4ldr+M/VmGfYJqtEdRnAA1N7gacMpXUtJJZwFAZWpudDVZy6RqprR59UXP2rQ6xG/mjvyXVMhqr7lhzuPTvYa5GxIy9eDuuk6Zw15GUJHK7fUgR2l5bxqBedBAYFdX8NQcWMwVhovnAngNWrRGrj+aOag6oNiEdWmXIBUfFpksGIsrqznoZ/vOTmV5iVniw21pzzRK8Kkr2QLBe9CRjA8/0ur9uQfkcD1I8uVJ8lv7qiPd1JbUqber2PcM3+AhMB1UvR
  template:
    metadata:
      creationTimestamp: null
      name: windshift-secret
      namespace: windshift
    type: Opaque
