---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-ngx-secret
  namespace: paperless-ngx
spec:
  encryptedData:
    PAPERLESS_ADMIN_PASSWORD: AgCxbrn+qx0WkfWMG7zLJ0jqp0XB/AdY7+1UbJKsBVMF5YQ76OT0YvYFDSwe2oS9RYIkgR8h/HSZa2yEMmd/ofd7UEoRzW6+SrsoIx5j549fzpYjt5TUxsah6/+blHmmQTJhqflGwdy1GnFmTtG71qwqx0SjJ1vtb9Aj+z/MdHLCGvhCgJASvfC6Qk0B6fER6PIYP42r7FDI4Ea/2RCPmYSu3UgR15wpXn+r5izbuXgYX4F2pEMPaWgb1XUk+YPMKKsL6IFKabI5N1+ymf4Tx+GvdskNgOiob1YwoUh3BM3IBqEBqWl6ghAlsQ9toTGqMa9JaGKYJn88VysBhgaArIsqD8tzuRK8ktwvKbSPfglNzAejLugTwsKHT9Mxlxk8A+uawUBpJETrBkOUOI7yu4eJkR5wFv2Lh9M+G2bgUeM9JkvybagI6om45h9lYqAsVLXFMrVhRdH6sztwuQggqnW+YFDDVqv3TMACL4/CD7Gbl6sGG/D5FPcJUJALAwVYWRvqDr0Kr7QNdyPww0JxdGeNPn8PEHCiGbYyR2sV1hYpDaGivCF+nv5IKGX2ww+AURab2ZHnCHczgVnQsarkpKGB2vKBiE5lv/UR+PPI/925ZkUhuaJXipoi/SGpzEnRewgTYUME3TsClWZaqFpjhoSJn5AjqlAE9jPWNq4Z83YkdhQsW0BnxeSVVInqoBBt9Gf7fyLcAfEqk61WClS7Jd9gR8/5WswA5bHUJwhFn7qfeg==
    PAPERLESS_SECRET_KEY: AgAV0M7I/w1MnGbwBohVNMrrgkw7xBdZ91tTiZdhWRmPFh5ggFtC4hPQdkFpC08iTu/N6DA9Yxfg370FzJSCKeK3/fbNyqv385z5vP8Qb/AzeM/A+ggJjutcEkuKMX0sRFlK2z0fWQnoGREecoDHkoZZh5FLiHIKrsqsmBaXqL21jSWaIjbDSRKU4b0k2PFpdX9AjaXn/+R/fD4GJIRMJ8IIFkqdxFoXcrDfRSrQzMUi+LXi6DCmyio2bD1DxI8Y9F3JCPxt7Usru3KK4KzLwWOV4ByGYS5MUT3pvGCoe6P/Bzng938869nfe1ZgoYAxTpGq4I13aFVzqTEfRi5Yepyv+O0uOF+xu7N5ldM2jR9JE7VZi8Y4zzH72xtfyvX0Lk9/Xi1xs6HqMrXlKU3TmwS2HXM26Z+IQp1PWrvpJfbZZoAynlXEa0M3cVDitoJE8NhGc1suga1ibab8RZ/5nnnh1mfQkXRitoeyB9fIxmhG5VIcVFP12L8d58pPDkjViE+Io1nCj3gSJuYK4dSmtSHbWqKv7hA3wadF2i4YT3R7v3h5Q0bT1iQV2Co7bllFrupPKbPjT+bYV2fwQ2/WbMEltDK6ktcvBm+JPiiG3QqMzF31Er2PN8Pe7luWSRD7Xp3FaQCfD9h1PJivWCFsSmu8hL9Slt7HM/LZmP2U0AizFUPutArVKs6COT+5ERP3bxGmifmE96jcl9CRnrm10fB0jmjQKMhP85ua4ejxiv24CnLnx0CIlol0zojvEhwqij8jrsSezjjyeLRheEc0jqqozAA4
  template:
    metadata:
      creationTimestamp: null
      name: paperless-ngx-secret
      namespace: paperless-ngx
    type: Opaque
