apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media
  labels:
    app: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
      - name: lidarr
        image: lscr.io/linuxserver/lidarr:latest
        ports:
        - containerPort: 8686
          name: http
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: America/Montevideo
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 512Mi
        volumeMounts:
        - name: media
          mountPath: /data
        - name: config
          mountPath: /config
      securityContext:
        fsGroup: 1000
      volumes:
      - name: media
        hostPath:
          path: /home/new-media/Media
          type: Directory
      - name: config
        persistentVolumeClaim:
          claimName: lidarr-config
