apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
  labels:
    app: jellyfin
spec:
  replicas: 0
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          ports:
            - containerPort: 8096
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Montevideo
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 2.5Gi
              cpu: "2"
          volumeMounts:
            - name: dri
              mountPath: /dev/dri
            - name: media
              mountPath: /data
            - name: config
              mountPath: /config
      securityContext:
        fsGroup: 1000
      volumes:
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
        - name: media
          hostPath:
            path: /home/new-media/Media
            type: Directory
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
