apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: shelfmark
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`shelfmark.local`)
      services:
        - name: shelfmark
          port: 8084
