apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr
  namespace: media
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`bazarr.local`)
    services:
    - name: bazarr
      port: 6767
