apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - component-media-pin

resources:
  - namespace.yaml
  - sealedsecret-gluetun.yaml
  - sealedsecret-postgres.yaml
  - helmrepository-immich-oci.yaml
  - pvc-immich-library.yaml
  - helmrelease-immich.yaml
  - ingressroute-immich.yaml
  - storageclass-media-local-path.yaml
  - local-path-provisioner-media.yaml
  - deployment-download.yaml
  - pvc-download-config.yaml
  - service-download.yaml
  - ingressroute-qbittorrent.yaml
  - ingressroute-sabnzbd.yaml
  - deployment-sonarr.yaml
  - pvc-sonarr-config.yaml
  - service-sonarr.yaml
  - ingressroute-sonarr.yaml
  - deployment-radarr.yaml
  - pvc-radarr-config.yaml
  - service-radarr.yaml
  - ingressroute-radarr.yaml
  - deployment-lidarr.yaml
  - pvc-lidarr-config.yaml
  - service-lidarr.yaml
  - ingressroute-lidarr.yaml
  - deployment-lazylibrarian.yaml
  - pvc-lazylibrarian-config.yaml
  - service-lazylibrarian.yaml
  - ingressroute-lazylibrarian.yaml
  - deployment-prowlarr.yaml
  - pvc-prowlarr-config.yaml
  - service-prowlarr.yaml
  - ingressroute-prowlarr.yaml
  - deployment-bazarr.yaml
  - pvc-bazarr-config.yaml
  - service-bazarr.yaml
  - ingressroute-bazarr.yaml
  - deployment-jellyfin.yaml
  - configmap-jellyfin-intel-init.yaml
  - pvc-jellyfin-config.yaml
  - service-jellyfin.yaml
  - ingressroute-jellyfin.yaml
  - deployment-seerr.yaml
  - pvc-seerr-config.yaml
  - service-seerr.yaml
  - ingressroute-seerr.yaml
