---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shelfmark-qbittorrent
  namespace: media
spec:
  encryptedData:
    QBITTORRENT_PASSWORD: AgAQOA4JOPbwJUfGcJRLSjMHVQpZDyFY+TO21kKNRnIiKrApOQLYCZ82mcV9T+jnWUHQRqquYVWY8KquQk6z0wcX2RxdtFCJkrN3/P/ew85++W60KzxOjECF6ymuYTaf49DTN375byyjQLKL9mnhvKkjcjNCAtIwi3xQ6DykI1Q86CFe4l0qDd59JJ2H32A0C+r8drxx1lsTbQ09dFJPX0BAz429cC5Cr+Qn8DbXfRtY9lOVZwJ9CFT0qmBtRlra5S2UgktpeaVL9ZEFPDK0agkX029j3x1RxsHgaRTJRmXPhI4QBoVdj/qIbKT5Gu8Z4lFi2/y0+ggGV3QnbPH6PqCiMcmgkggMzOlTiSYO6z00qzVwB/CphOfL9mi/ajQkxLi7GUiATMmJz8ZZaqjtHTpaeUzVhqjvXqOXkw5rox6Vtg5gZ2SOwdiYffHP7aBCYFSnTALv9XilDXLqjl4TGOFRhWe4qAGhA02rMVhEnGHUSbgi82mjFP48PGlC6Rgmy+3tvD/kRt4CeVZ/2QSV+Lm8rVIx1WporF+eFaVdUB3MI3x1+p/5oej0E3T1Oey0POsTiMkMnAZV4GLaORgwN/CibNprk94D3gDmdmfI4oDL4UM8bUSUcqzHUm/0AQwwHkuj62X7tzC1kMibNdGGIJCjPNzNqAxxgjVorAMvewULaq93NH1EUiD1fNLs1zmptUfuw+wS5s+o/1FpDz08kQ==
  template:
    metadata:
      creationTimestamp: null
      name: shelfmark-qbittorrent
      namespace: media
    type: Opaque
