apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: placeholder
      spec:
        template:
          spec:
            nodeSelector:
              media: "yes"
            tolerations:
              - key: media
                operator: Equal
                value: "yes"
                effect: NoSchedule
