---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: atuin-secret
  namespace: atuin
spec:
  encryptedData:
    ATUIN_DB_URI: AgDhOI7FNUGNgyhMEmtsNSxl53235atG3E5d4S1EDQdaSzUWiI8GHdaxBE8kDmaCJrmSR7SJjs8BRdpKYs1V0bcqtnAowl4PKhSuOMX0ux9bFTREr8NbH8vxKmMrXtuPIw45dsDvgf7L9iYf3x1KKSi5plePCyjssRjuwyl9BZA5YohLwFLIWB/gn0pAUiqyXe+jbHtIkko079A6549sZEca6iFh6G+J5i8e0opkQDeFw0+1UN+690hCENaTGsHz5eXk/iDlGb0rAPH2b658OSRIfnPdlAR9Pe5PkT0MgQHToRv7otrj9VdslNMu+b+uS9BvmrnaeD4xtb1ZYJwZZVT2qEOCJe1XO1OU6wbTjOMUlrTiWQu1uQceMe+E2eM8R5ku95x50EY7rDA3cZOB6YUrp+ZdSxq33lAKmlC3W/AIqgZZaX67gbsIRBHsU0PR5iUBRGWJjIX2g7sProNUh0/TPDemQJFgkrFLSWLP/kt+sxF2hFQaE+4qNELvALaYuUtkXyKr7lHcc7kWKuWrWnzqfmljgK/cL3d75qleSZ71j3iksQRyLHaeVcoF57TNGWmnJa/+WbX4KxUdGWrnF8xt0rLXA0+Y3g2osNTOaiNtUBw9ZtilJ1VLYHf4qmA4qTU2PrEvbriFOnFYPUbv6URYgRplt8VQVNqZIW0Bp1NSzXHDPJOKWayTPreYOoRCkhY2D07/Pywnq2ktFSefztL1Ffozx/PRUIUytvKM9KViSldsrl4eF/1CxkUATVPzdsL8UAQB0mS8sicwhCs+DNuBgrVy4Q==
  template:
    metadata:
      creationTimestamp: null
      name: atuin-secret
      namespace: atuin
    type: Opaque
