apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hris-alacaba-org
  namespace: hris
spec:
  secretName: hris-alacaba-org-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "hris.alacaba.org"
