---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hris-smtp
  namespace: hris
spec:
  encryptedData:
    SMTP_PASSWORD: AgAz7+Lt5RKwe7bKO43mwj5v1imQE4zL12wwKuIu2P3EG0CyJeILz4B/569ymoT63PqHrRBL9H/g/sy3ecZ97zJMeeM6LZ21RXgQ2MmOFb5a6UtGE/IQUjOMXGxAr3NByBt96F8M1Xb6sPfKgHs50PcZLWSpijg01C0hkj2D34l3TKFHpuyVvIA+yFqGzbM0VPeYcLHU4+DWyovFTpCf1V+b8rDitDO06RYyARSDCuKSpTgVG1W9ejd5pwguQtHrXf6Jyj+036uqYdHy6E8HgUoXE2y8freCvvU82m+saFXvwS89M+7t6KkoduZ5zyjUt44hoJQSOm0QhrZGOOqVnwsN/w6FyNkW48gZRmQ9B+tq9Twoo8FOQWoDg8JjTuyejf0CYDM3F3AGyIbz7AWN8zgREfjythTVI1KsfsBGBZ7smH1Hr4WgXR0OLn3O4DQ3j31JpfOc9xOHzDerU6sxdlwwaGoxXbGNwCiKlyPnFYe7eprF95+WnXEiK4EoM2lrQn5iOMGfwsMz5HaDWrLcqtL/JWsV8btE29dct+T82rlCOL0AAMhuez+kKPKca3XiS/afepL4XLi5nMhDFN5ssIU+xkip1tQVhFjk/Kt+rgnzkd2X3nsV5nBouJE/D1t8Je/027H0cmYtfYLLiFw9POGp8UQcARbiNHBtfp3Eg4hk8MQMKbRSTPkPMvxLxrp9tswzh3Fs6G9crtJN20qbz0lq
    SMTP_USERNAME: AgA8BBmbx8+YU85mfnt83jHYFZmuoUyFf2cSs0sAhWwW2/j3w1osqdxdIUk9a9oSEHZSvT34TtKJbxXk0IDRGQ4yXSQP3chp7BuAvlLstLPLOw2Xr1KloJoRT0a2IeNceSciCLw084l6TeFvrij5tpI7H+SoEWPFEm7Wf/ETgcNxHpfUN41mMOHLrwRF/+K7iwM6iFlu6tJfU8mvePYkvQfWJG74HXQ5NPstFboI7/S6ShzklhgpvyHlayrx54j5M4T36z0+GgLJuQk1NCmTOLGJZi6ZMgLEoTEK9B2QU4cbAjaW2RdlG/Z4An8PrW+DMhTG423khxvpWR5g0fDYcV7yX7nwqfmQGBstRJ1JxYc4+1HbztWmScqbU2IyL9XMpVAZaLMDnWR+A/Pg1T1tG1lOmhjpd8EF3/AIGVxCH3LVTQYy3VELwv1EO47nDXXsR1PoJU/09TDtgMzAR/tcVaCWQRqcxpdg+q8ZxZzF4ZFNwoehqrdZp5fpDQVsLPrzwKWJD67uGZMVc7Ys5+jN/gh7zkDbDOB65RgkIH9u6mSIHwJu8asO1s6vsv3Kwb0Ig/TS1mzTJgTshE2OxVeIV3F3MEfb1CXIhwYbX1RZ8G6ZDn9zV14Uxc1efY6LihYXvPE/eaVtfuGyZsbhWNg4H9xPmqLyHCHi+m23CyU4BFx2qU7u6kck9u2mhSWs5G3y07dcJesc9ktYCO9mAtnzL4wpeePoyQ==
  template:
    metadata:
      creationTimestamp: null
      name: hris-smtp
      namespace: hris
