---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hris-smtp
  namespace: hris
spec:
  encryptedData:
    SMTP_PASSWORD: AgBd7UUVSHsU0s/fftWVNgnjLwZF2rp0Nre1shZ7tqi801mxcg4IEvVu55joBMTIy3ACdMWpKK3TfEi8wJsC8BNm4+jWhlrZ3eYy+9VaiG9i9zugOEXWvOksx+ixksEZ2yUXSRCDVG31d+NpMUjeCtCvbQYumXM3arjtERdUz+gaOFJYKABbP0NLvjwA91wQxBYVib1hLqB8VAGeNnxDAMgl3gb9OfvH3+MAWlneCr3ibKfzC2M1yH5MYHT4BJRezQ9G9JWBwHlOR0cc2AX1TOzKAwuDx+dJFxAg1tqruU41G4p8Eg3dFVv/693cCtqAzPiey9xFEa+imj+tLQ8IInmmdwId1ypc1Ff6Z4yrq9s5Nq593oj1PInCntRKDVpcBATMYjmnpuGYl/t/oW+d0pVqQQ0LEXI5PQw7Bj/5gyu6ZBsxw3z75Fjf1FQ1bMge9yhdAG8dtr+gvUqbA33o+JOdIkzEQcOFVI8Ok6lm40DhjUR5TproQ0MfQbnMQroJBQxS8ho+EYwOGGmMY8MDXEo9tuRXp7Gz9wF6q96cpEHoxqkrUkXJRbQ5Yi0Yrl5TmQNwYRJcaiL5A0bs9lTU2bLTGQyViYkt20IQNza7koWI7mjsW6cuPerX6deA0RB9VBu1zSSdrrLgKc6u4vn5cU2LKi14cWXJs45x8tTPqDfmXnUPwqh521OV/3ftUBhOEPBMaluaxrKIEXMDrb+Qnq4G
    SMTP_USERNAME: AgBHVSVpO8iskHlNWYCRMeg914yliLuA6k48Jdx3RVItBfVD8tfGh8gNwtq16fvJw7EohQfJBBTml3i3B5WfqTM5y/YirtOuhz3OkDv8M/ejGPDT47k2RsXxWhPbhVrHlspGOZHJWrJqxutbIRuaHngB2cNZS5Jz/3Lldvq8imd8DuT+ZoLCt2HFKDsv40ZPoHeVL6xUaTWujJSDCrEKsX4h/K6Ov2CcL1AmZ2P6iA6oojk7hhcDnaX07gzC3BaEC14IZkmu0bl0HndpCQEZRrmgNl2LhhN8C6AgLNYKKcZ9hebG+kZ8O5UQv+zZyskgndLa4aXz2IVji67MAx/or0S6EnU44VEukcAELIrPQV6/Ji1gqfalp5E110RlL6iNlrxRoTQj5hb04L1k2WXfHBGjeumU5Bm4crPCZrpssxZsQiWKwdfXw+rDwlKlNucl6F4oOReNxGeHa4ZnR8CB/SGxdWoFwgElJMWhtM526DXN68avxM0pq1yiFGsWR1rCM7YJlmFM8IU7oq8SPF4GKirT/k8Mp2WQxnNvzg3GDRVtndzM6jJy2WJiSOSETfgHiFw9t0abQA4LNj42aWUVneCycAOdhXYPPUuHMpcAp9bDKZgezmod6fdra+VhIZIOIfq8MZqcYDDvI0QlBtIo9aDmHRbb18ANrEvQ+wnm1oQY99tuEMs0csptB7v/cLjqNLGdefJaMXdrzC/RK9/QwoOkhBLhSA==
  template:
    metadata:
      creationTimestamp: null
      name: hris-smtp
      namespace: hris
    type: Opaque
