---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hris-ghcr
  namespace: hris
spec:
  encryptedData:
    .dockerconfigjson: AgCFNoqIkK46kYmbs28iV5trDWiOSBzf+zPe+aGIUZGDgkCqbbspwSwCpfOgd5uLKmYNpchC4BOlxirOoiWXhGArFV/oSb6RrFHw9h41VPYAsTs0VTAoS9cuvG88my+TePLiEFj2o09zniH1OnppBSD0d8V7tJOV3PtZkgP36TiIAhm+IrEK8vvSQk9FwbKRpyP9MUtDvW8f5MuBBVV21OrnKjhmOV0e7b6mzeYzXo4khhTktKJD5oAQZ11nzRFvOlD2SZqGszVzsfGFfCHo9100w8y3bMffgUmROeB0lPTsQDwjVPDIerzybRZMdzYWvebU3ZXx9f6xQPeSDvTJhHcahJ4ieI6ScKlVBJ8liY6+OWAhzRQkU3FZ5RzmijJH917LHgiXFvmxkbX8K1uJiRyw/meqpGImRtCvLf0hwKTK/XMXDj0Vtexf78mslD3dsq4jHPjYBcPxzIeO342d8tGmsGq5fQbTiAtSVo69EIvclCiCNW1ma0AjuGistIcwG6x8jPsR6gOor7MAs28YFpto3eU+Tr3VfdlJDKRC61z/eUgfrSBwOWE0SxiLLrU0+J1vCmcm6wWLMQvZJAQxJY3ZsSnVbKGDex6OKO8C8PLDYezsiu0kVnK6/4DpoKKccaHsHb+3TPJve8EjM91S5dIJEUhqBkFzvbkagw3DBUJs4qsjQ/OUdxfafIgD60WG0UUpl/JGXWFWHuxTr92ERd9xBodrEy06OieIwgq1hIJGWRylBhkd/Tc4Q3DwvtMQE7eoeB61RNoUmygQWWI5lC8F5Fhr3tF0zKrm6ifS+pDrsaTtFZ4yJEboIuqwe65RxgQjaTgJSC0Vb5N0qqa57KKyQJrPi19CftQRlivDP+Q9FbapbBf6gdfm+Yuv8tM2JsjPlBCM5sgx5Dba7gDGEJ7fVU26WQSxqLt7TDNGmDdwtqrbRxHiGXOr
  template:
    metadata:
      creationTimestamp: null
      name: hris-ghcr
      namespace: hris
    type: kubernetes.io/dockerconfigjson
