---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hris-ghcr
  namespace: hris
spec:
  encryptedData:
    .dockerconfigjson: AgBD9DIPFx/OeGHIGIdGS5TGxQjE40abGuQ0iUbV6Ha7r1HL8JsfLXI4K3eWLNOGVoMY8RY7AE1Tr98by4LyOGwKGLMwg1dy12xE5WNRwh9Q8JFco+JTKc0CsTpqo8WA0rMAERf6vxjfkVm9XQk9Qk+6DmNDClOQApCXueoUh9Q/KwaMKBNQ2GDUwut9053kS2V0+KmoJF+Hsx8mJ++dYrQB/d2SIYBEyJ+5xswoQgkEKFm+KA5pHkF48jacltou8cP+sJr6jSOs/wkrXFjs0dCmsAedXMBBCCbNHJaChyU+uag8gxLCV4XX1CETlj+eyWIZFYJ4d7eQQt2+wuHSZ7LPTLvlQOuoZGDfEOrE24DzARhvQEsDLgQiLlXQNSL1+wGzQktuznBvgiUyt/aaih/yvhbL+tYF71OQj6BLzpvHI6aGsgsY8x2HBHx2wVlMdPubdLm0wGQgejNCzVjL2cXUqtEZ5HhflFMH9JnClbWEH3f6ex0gucE+Mj5RAZda752BbAZzC81BDzlxQ3/srgSNR6DBWOXrTxixJXyBSC6xO5RT++TGdlPxQ9804lxdfnycldmBfOAir6fwlTQyexkH6qlMMomH1/sYOWllldB3CCK/HZFfxwfq3L02GMbuVmSM0ejQ+dNxWvRnl3qbW13i5AUB8ALEUdkI5thcdBB3suUCEq/7gZsmNpsHxJjNsiKt2YeLJW6H6mQGssN+u+LrRkPxEJnEhi314UBKcbG01iuNud/ZTTxYm2rWqv0T34Cvyxrp3ffEq6BJrCNsSHtrjSsIHz1Tk5F/MNWUR2J0I1RQOre3qBIn/zZgpvp3oZeJZf/o0v8e08ZYvHXyNiCLOeAiGu3NKLtZPwZ3X4up7YGQF2/LACaxpUuMo5us+xIH9Rdl/w6bJYnZd5CGvCRO4JfoZ/hpPua5ElQCFoi+8kU=
  template:
    metadata:
      creationTimestamp: null
      name: hris-ghcr
      namespace: hris
    type: kubernetes.io/dockerconfigjson
