---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hris-db
  namespace: hris
spec:
  encryptedData:
    HRIS_ATS_DATABASE_PASSWORD: AgA7YcDSFWY4Ku7Ur4V+ulOBnlfbAdGJZ8bzDnnxqfTAi5wrjvG9ymd+GrjRg8yusDRjLku1hfK+vwmm7qD4yxtnZpusWnBD4JPIMKmxEaj0W0kwhhoTKAIsmYL0hZWtd1IcrzNuoDvTzKwSy1IuTT8ChhH6XZy1Y1JBc11N5aPDWYaVeXP4QL+6BNLt6ssneL3XHn2dvbylGR9TC5Zktlotmou9ew+WlA0j2elyvbT0wad9sPj3a9BQk4m+kOoz7rgIk8mJ47zC8SrvjtalY1AZRU3cXSslJNoFqOpDFLmA3OAzTcpWrut9KFXxQyehUzldX16xc7sLQpPEILti8GdYFr8OgaQPqohHsOpJtkWRO/WLe8YRaIPTo6/uScmT6lLwPtrBs9auV5ebtWa2sjhjb64bBUSl6XV7mb5M83XaQD+sE43o8v/4AR6Sm7K9f9IMYIITwwn56YTjcgNf8/6BRuTezxmFN0eSL+zDJel0MfaMKv4wvvf+RVUGG3w1O4cLpx+pjfy6gRjkMmqd6zZS71VX9SSNatU4qnbNcGnJF8rJPemBRtRtOxn00NJvbc3K8Zrr89bbtgTBorCwjcnfD8NxKt34yrSLq9HZ7hgFuIrtbmQeQlmyNLM01/kAAV0Hp7WmcsWRLlMRkOkno83YWw/knokgno/ZuNcoSlBytKyVkLSNDFHat52xPn+NifLeAZoQC/HHla1cqqn9nm2PYqmaJB+9kRw=
  template:
    metadata:
      creationTimestamp: null
      name: hris-db
      namespace: hris
    type: Opaque
