---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-registry-auth
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgBBxdphYl6II7R22XJk8MSMYOTGFDnf0tajfp8PC7xHiCkLzqcNKR388YwMaKcKGMbx1gn11y/OxrwSpnqCSZ1SDKIJDKCr4i0URVQt1IKQfAz0AKz5OudGryIDszBZ+TrqGi54o0AzYy4vpBtyu5zBn3M+jwTiyOv1Cs4sgrBTTm3a5XHYk+2PbpcDpM7r8oAfJbsMSQQo4ZZbSg1A7OxRmSc/wKLrFE3wmUf1tviKy1Beb7/1m3z8XW2lUKMInlqQfTbBQTn0hCAfC6fW5fuYKgtJpfb9h46KurIk8G/yTLsOkHWPJyxS0mUct/gV1Y/Bhw35JlIulR+SoaWHyc0WQEDPCL5QCCwk6Ow1+5kOdk0rBbAvjJjPCScOjhzXa1FwwZnXYWwGy5vxoQBbNzgL/pQZr4IfWqkWNrVtQywTHjb1UBj8JKqjIEkEt9Gajs15n7apE+aaEN1uRwEqPm00b9tR4AtY4TiDC1MY94zC2A1tUxCog9blva4l30+1tw516i9qAuaFTnKTYGZ89Dq7HrlOxMHRJqY34zjYkkpDzmfSMveSOjcRfUzgN3r7Lx7MXM0X8MfBkjwd4N8AfhihAAJwsKubXI4rFNgc9g0/15TlTann0BY1jxh2SUE5sCUTJl2ZBaWujCyZBTqH+o819rlGHPIc3d/389CatqVSLA7Sagw8oJb8ZiSyr4OhkQVhr7p8SDrvJ0IXInDOG0efEaePm2N8/mrGctmVQYzC8iIrdg84L+2I8U9+RhmUl9k5Ao6ltbT6DCQeOfAe3tWBcR1F/leSCjN1zAGeayfPsQeYDJlk57z9PXw75usnNqq44tevstdE5vS2XDxyojWa32eglKvdhQUkGJPZbauN655GDIWiKP/2HJ57zaTL6slQ+xkf5SaN+p8Iwx9JF/YUwO1nRyZ1jdm4A4ulGbkRXc0=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-registry-auth
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
