---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hris-rails-secrets
  namespace: hris
spec:
  encryptedData:
    RAILS_MASTER_KEY: AgBZ+vdLvI/FWV8JaHaE1pO6w0kME86Y+dIHFAgFtDyOz/D6QdMJirVjMDBDrCN/8KlN8nHJ8+/6IPpEYEskfwqOPDKJRAC3Mc35pYF2IYDC1IbXh3BTHhT1lWaeb6sgeAAWXJ6EdC/yrXBKKmJw8iADxZrNK0D3uEQhhieXcthQzgFXzuGT4ymWrZyoxkoIGiOo+O3ys1LsOaUsg4r5CzUrSXh61FBkqundnNyKA31z7NZE6CwIDtuwKQQCdSuJlB9OXk03Y2Km5I/pl+c4EF2X4vMqA5qaE6g9VJYFSj9OBW2vzb+BiOj5y33fzEDmt7yefXz9e9iFWqfcJwNQNdFQmtCMgim60WEFUhAbsQEqyNWX3qWLu6byWihNbli1HpqtUkDtV0jDjCAVLBToJckSDwmkTV6DWif+5XZ22Fxnt95nwfn02KBhqvV4l+l9Y4BvvxO0tUhXRhVUveOdP/KKAyMoX58BxXajxA8ZjO6+w2ce6pllRBRiTlZHP1DdOkHl0Q0PVwMhnQOv0EEhvjv3m5w4ebKmMLR/kKE1M+SJHBYbt35bmUDUFOvHhSGePUIboCQ6aauc0NCuWgMg8CLZDG9Qnz1LKNKdQsgp2++qQBdGzEii27T71m/8YzolLJUBF9SJ2fBgoI+DyCxXW7gQRq9ZEUQhtqDT5CUpY/fIaYw89qtbzbo/IxDF8MVvitaU6wNPFp9283sSaSDv6vPF/GGcqf5jTQ3V8bisorXOCg==
  template:
    metadata:
      creationTimestamp: null
      name: hris-rails-secrets
      namespace: hris
    type: Opaque
