---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hris-r2
  namespace: hris
spec:
  encryptedData:
    R2_ACCESS_KEY_ID: AgCNRCwS3XcWj+RTz70cDN0XmjihYtdYwuzNSlS+BQVukrDg5+FDQBUjnBauUuJC/zj5yK622wJtuXeRDWgxGR69gb1eEOUiJp+GFNc9uoovdICt3uhxNuXFlUyK9gmsP7R+UCIkSpwhNCTnH43Blx+H4DxQzTmv0vG7cJzECIyWq+15nvDljWWRH0ttlWkCEf5Nhy1QIbrpfnCVHtPiUMtlbqc9DnHJt7RlrAwWUXkfRjQEJeMVPCKqMFwmobvea/q4eA1rmS7NIMTrggxzRvFcyQRtfkDcH+2pg1zymmRnEO7SZG4NjDJbcHlv4atgwK66a25P4o5jAR8ys7qN5rKCGiW1MbVDDve2RqxtWgrUFKfUxyx7HaRFU6QqbEsjPQwtdZ3/Rfg6/j3lsBtJtg3gWlD815efRrhWmRT3KxUieEHjnSrQDnpfXjQ5p6NfVwE50pBE5xXeGDsYgaPcwoCkQ8RB2DTUeQz0Hi4v72QTnrFzijH0wpHElobWIfu4pjBqLE/5lSCbeJS+DmBFvjs86W60N00Uj1VusiQUSgdLXvBKonGLf8XMH5VXfgD62Pf2u5OC2daAEz7GZPpGGsFudffRuqyTs0Aqt9nV75zXKHVJSWWdQjDynColgkhmsd4JMWHwDSonVd5XaYx0X+5ZmjZjZSsfPJqKfwxA3MpxvrgR6i15VizPRfud94CYarGNt5pYpr+cpFToV/QB7kf4EDJIGml6/8hr6CERaYoVJQ==
    R2_SECRET_ACCESS_KEY: AgCWxt0pvwHaqbI2qBxLXO90m2Xxtd4AKsCBSxZVoTFl00BwNSCvmBgUBS6ZtLAeQUkx15gtFrx3oeXKPWo5TK8uT3x57SFlIe7qvo2gADpaU+8APxxMXKN2Bk5yWOVO4tnBnkNciI7miQY2ZRmwndEe4KDxk/HSUDuqJwzLBeB1kQflUzw55puLAFFp5ptFUF6dD5aYw1tJ6Ps/RfkoLuaAAXuDHNZQB615W0ioSX/uS+vhA9gArxUHGAS3TaTi6pY2to/pFSwvgwxnR9RUJ/6gz+vq+PGuaGUpU/SyfRisYHX0C5szvjVW3MqHQRPqn0YC+T/ysgJ81XkpMT0UUYVWPfZTfL+zKzBau5zKuGeP0ds6PW+LPYjrECeHEXlLTe+Tde+/BA1P0yQfD9b1i6GWddjGf9J2CW1elu8iLhnNb9K0v1Z0edmlW+ly9eRfizCwojGRQEoO9Drki9QENRVxtLNGuG0A/HqESYATDgmsbx5JULb8QDM0IH8C4zbFZPZqG41jg6/M+JdDrATiM3Agt0XBV0lfzHZeVyRK+GlnWkIMfN4Jc4GTbKP8WvwRbrxTSbLh617vVnEpCbOvRlZk8yZ9TDuS0jgSQKrzjQkT2mZxu0XmU9p3E7q1NJPwxRN8zQfp2rAn4+H93gYs96jSYzLRt3V886w1lwcGq7scqRRaCy/zFyp1hoRrXdib71E2kRbS+JOfchSbjCG+kCdfA/ZaazoOC4whKxKkUwEcfWSkQm3xndgjaVI6g4dBwQJrdk8zXatz21hidL5GFIJu
  template:
    metadata:
      creationTimestamp: null
      name: hris-r2
      namespace: hris
    type: Opaque
