---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-registry-auth
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgCYDbzfqthTTH3NTe1nptObHSrwPnr/1KTgjGG0asmie5f6gK/oixeJEfyqcgQfS8az9Pbz3uAzQaoApypE/8KTCdTk39dEZDKQeoxLeOIeLIWVZlrjNBWVYdamsJMiNfwJXq0MlDyfZvtIee01aRbNmH4YfxMnQgj7a2AUmyzh8Eeqg6DeJZNST7yWagESLEw7TG+y4AtJPZSclUhci5ZF2EI5a81tV4Ci441yS/SaloRG3Y3UncaP7mQnNCg9CczFtosNftb5QOJc2zhAbMKO/ib2Yco6FrimcN1m5XVIRTHmc/pZRfyDndc06PiWdR5SP3+zw3aX0fqVC/LAv22Am251vDFTbM0BhNMZ0qaZ+tWWgYDYseT2YPV8cRWna3S+2WUY8p8gRMweUqgeIX5cmaQ+BIcK82TkItZaF5Fzo4OjORAYo6kb+j0VGB6poaMbfC5S8y1khEiNPrV/qF9zsWcCUZ7n1wNwDsZrNaRKhbSsLy7qwP/kx3hEIzVEpn/f84lCcM2C9OvVPPaYsi7wknBA8LQOFR9qT6eanwdnzxmmwQueg8FwpXm8GYuRSd4a064YKTNiysvNNhQkyWnrHOO/FkdfV8+xh3TyfEhHF29I5Cw/3H73QDq7ZZ4IM87GPOqHxzNznJneeg4KiAkI9M2srxCnxhXKFbLtfr6YuSglGjDOr1KCRQzApN2BSbtsPsiR+dG+MlAxQCtMMEGHqzQp8usZt8NTksNhVDevNFDj0XAyemumuHxpLE/tiaNA8h5LIG+sSaiFnmcjic0ghsTbB45bf8hUPHPp5kT+GTuqLvDM4VoD4PI3Q1a3TQTk/dbqBPVWrEPDyfkvpcYndjInj6021PMdVOXpHj8ZX14EByEzU3FqElJ+z+kKiSnikX2RQNdMoL7iaEp9yIYsv9kpwcj3AJsfCIHAqVoqsAQqFEAVHMSe
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-registry-auth
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
