---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hris-db
  namespace: hris
spec:
  encryptedData:
    HRIS_ATS_DATABASE_PASSWORD: AgAWxkpKR/vpbQo442CWZi9MgTYTr3Q/hepkC09WYuKNsdGxk/CO89YFdzTmP+doGOt1v9I3WyM9U5G49wEF8Zx2hqKCmE2cxVR2vNszgNo2zXtbTGBpuErgPr/Ei7g6YQVzEqAcFQ0/JCSRa7SRgOU2Y5DDkkBBdnRlFeEPgIvUYsy+sl5/txxbcR1e/dTpwR1rxsfl4lamk7EjJNJ1BFjPbF0Ap0kvQ1ywFzEl5C8ZSmGzT0UH44u8uAmdWK5QONfa+S5pzjWpmr+cAU4TAm93bfA2gOeSY5vkRzI6nGFqOxgxzR0tFvhcBVMUGLSsCNRFWwO3+rwskLq5P47MmgFlEM+tshSaZFwe+UYPP9z+sqXzOEIwtjdaChQyLrXR0NQyp0tHKq16hZpEs2OObpTiiIyqx1fxAKsXq/rjEAFVUR2kGdCHlihpZjpn4JFYXhSWVG4x8DGCm1uUDi5B1tpKmucI9X4FK6/4/pUkhWKZ4sUTWd3lfQ851kjlcrE0hAmTxXcK1sU6EytF1WPq0vB43UM27Qq8+9PNrtSA+MnJqxJamQ9/Q12EC8QEUtE8Ov/GnOGdKWPLdCU0kUUL8QvoxFA8ljSwK7B5O2PSI6s/06iBSZ+1RBMtT+PBtIkuewpzrwhFY1M45HCm9d4rOEUCBRzbJ1Hgc6/xz6PjHcQnzzSjU/IvirFAt4+wgalwqD4+VSA2bjDyufslSpcERIHUreEhGNM/1co=
  template:
    metadata:
      creationTimestamp: null
      name: hris-db
      namespace: hris
