---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hris-r2
  namespace: hris
spec:
  encryptedData:
    R2_ACCESS_KEY_ID: AgCz6PQ6xJpodwQ1Bi+TIys56BxOGYxXWtFoXWZfGaFTmlaJpo1mbHhvsAMTjPV5aAnMe+GrsusLOS3Bj/+Pb7ZY1QzSp5AI9NyS+bpRkrTZyXxeEs81WqD67bjUgwumA16F2Zi0XelMgYpc4q0vX2M0EN5XY8f83whNC8IpQ2vR7w+MA6Tq4kOfjcc+TIlHegAluLhnMn8EC6AtLDXW7gVr7fyNh/4JcxNDyLzIt0q0FAX6xs6Ps7XYpiY9s366vP2OdspAH1AaRo+mcmAeGSTaEWA5gQqvLrH9bNMLQ11ZTQdpH3Lbuo9WbZKHSdDd7RHkt0nkrXuumMOz/BzYX7AW8M6li4R1Lak3+9jTyuGCQ3xeEL9clMoBvzvQFkyeF3NvIE35ETliBNobGKYVVWRAuShEjhHHN9IiR0eLUKOTLD9emYBaMRp31DkJ1ZH/nPhhQWG8qwDtYTzAK9evcGW5gDDrOukrL2p1QJX8idY0P1+ZC8GVdN0nCp+MJBEl2Doom8g4Pyzbx4raYxPGTpny2IrcK5BMezqK7xavKBKUpM6PdYN6f3mwt9XKwVfZKuoioVC96s2wy6crDMSTIiM/vT9G8fRZKcqv+bt9lAWwqZlzyC9CSzOH+XPLsr/x+eVnRA7i1b27XCdCeMVpv61zfHGchbY8EfQT3mAToRl6w0hkBTTcY9m9bLEeYYcc8gj/iQxKwil6rNYVU48P1r5HQk3YwxTQjmfYaCuZddWXSw==
    R2_SECRET_ACCESS_KEY: AgCfQne8ILuX9X52XX2yzDXplr7OYb1ZZN3vBYzcUhKBtoplOoaPzQrlWqjHW8g6/OxJmFEzTtqvKJC/RS+GfLCyoAxJje30CKKdXvaQGpFnpuq44ZPaCQImim3Pmm7WUt4yRGJBXA9zsfA6Hx3btYhK68J47S85hm5XoE9wRhpxBnu1lD8Px3C5kfX9+N2aVptBhpX5WvpCCWW0VtpDsWWPYUt96estW3jCCNV+grswQMVrKd5uZNLe106imPwku0HURJE35ajW7QUe6NoCKUquYylyz0EIcz4wx0tCOH3kzcZG49p+ZK4gO8iDVyvX4qbhyBeuz8JMMV6medt2l/Y9vLSQnkuMuXuiBMgOnYi3oxEMwhiQWq9QdRq0P5eVfA5FWLWQGHVtnaIyLp+NysmqPIJL0iYcFtmQk+v8qdBy9dfW8HIlg9gU3YA5t/MaQ9CBVF2kL1iWQ/iCNe7VMIklKWEKGtREuubPi+3iHSieZYLvK9BoxaLLZ+gJRAv93IaSUm3lx1HKcJD78LdbZ4/skfg9O9XSokxJTZnWkGAgaacfpBqlnv0dV08ngcRsss/9U4sbjTsQ0kS1CgUjwUyTtYw2tI+iyHvWj4u6ILU5GolXj8+3HhmPcLq62Dy+Q/2hh+sOQNafUps2wwoKiPvw90iozlkNa30elsJeSZHRhpoRoyVRcMSTpTY3NAcg2RVVYL/hE39jyQ0VQTA0ZfQ7KTpW4CYrw7hggqQIaFxzEft6V79/i4znef1b0u2Qz94Nw8W2YSJ/OBPwSNn5Xg8U
  template:
    metadata:
      creationTimestamp: null
      name: hris-r2
      namespace: hris
