---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-registry-auth
  namespace: spec-frontend
spec:
  encryptedData:
    .dockerconfigjson: AgDc0Lp506YDjcqyTEmX5BZcXBwjAT2Yx6UWGu6qMBhxiZDlKVYLy9C90dmtSh8Byjnb/olpwbWHM1A8fV0RqTQgF/264ISI4wGmCXz3UBKekUyVZMObgHHm3CcXgIYFDcJfkGF3pgveu8Vt3pYFLVHgQNJcC+G6EEHXcWS2xbZQNV7srEr+2fuP9LKQ2PPF2Y8C8Z/o2xQ2dyuFqJrXqOVu2Q9n3atpQLFYwFAex+ouHKoWnc9UdFZpd4M7FWF6ID78AHAf9VgyJ7BNqrKuNqJmJi38J6lSUtj2NmtKvE399TwA5uKeRU+fMRcSZPz6Fxg1IybdJft3O4c9W2ISNhhkfDdUybDDm5dgccKiq1yNjH95q0N+mYzOeLugM+4lW6NvE361PPTBEnYPqSxFFLaPDZbCQBQpZdOVJi30EtrQVj2XRMenAPpjehx4wvgF3K+NQHNCUh6pPKqSFvPOVP98tJepPmKbS8TMo/J8Ril5vXKtehdSiPuUQj7OIhPcB3unNu7akxGhaWqrtx53O29A4HhdZL38zED8e+sP7phwBWaUIQzYTDQhVq4TPxCe+Qqb+vDBFkdbFAtcRvrbPtUxMwwIaXW7Qmj5I5+KXjvojMgoeVjYJEnO6QAarKXLrT68IPj+aohdZFL5TYDsAxn2HflbH6ShjCZOHJipGraKipJiRdRvuS7Dizuka2MJVeZg4AIXiCYswXMarpKYtXnr+OfVMewNVEBbMpmwvL49GoOnFz5dlYsKHS5zc9Jp454x3pxN29dfZdS8WV6w3ZHAF5B45br6jvkgiTA19Nj+j2jDbOJeFbUA4P5eiNoywoVKeH7Pi/o66ExT3ZVqJBC90Lb6x+fApb4UsQcS5pImelg5KJYfj0QKeTq1fsA/g6I3jSBgc/y4gQksmklmjWQ8Cu914bBOz/X7YXsRKdLhkZpHCniILpCF
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-registry-auth
      namespace: spec-frontend
    type: kubernetes.io/dockerconfigjson
