apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Flux will reconcile all resources found in this directory
resources:
  - atuin
  - cert-manager
  - cloudflared
  - cv-datastar
  - floci
  - flux-dashboard
  - flux-monitoring
  - forgejo
  - forgejo-runner
  - monitoring
  - neo4j
  - nextcloud
  - paperless-ngx
  - pdf-unlocker
  - sealed-secrets
  - spec-frontend
  - traefik
  - vaultwarden
