apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Flux will reconcile all resources found in this directory
resources:
  - cloudflared
  - cv-datastar
  - floci
  - flux-dashboard
  - forgejo
  - forgejo-runner
  - monitoring
  - sealed-secrets
  - traefik
