---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBcCSJH5IARbkFW+o/Vz+vmU5DLqJOJ7l6kDvQI7bVMcT21fZg4Acr0/7NOmOKogm91DI2E/ImHhPdZOYYDhuPFv1D8RzagjpnhgS6asW2NVLlScValrQWtUhzo3lOtkQYZBbeKAkAA/yUuUnPI6WgRFWESJMAY2DBZlfXsq/o9FJRlljM1htWiJeQk0KbT8c18rhT9bvIJvMfUDDFKePpEbeBreQ/Gfk+Pw2qvDmPHYstIUpdsKPtFThIv8n7ezSOVwRPgRRm/7nvC+0YqK0N5aD8ZS4iTFlM6MEI3X+VVrEDDS0hT1MoSqTBDfSH46DtKPIA294bKrcdHSIDdfpNpkKN8CSVph90WH7pbx81Kl3lBaGp6Oc/4Fnib723jW6tTqPa2CCTbcOP6p1yJGtApnh9ih+MgW/kk5cTEW1Gsed3S6gNSD/x8lnkybyyvV5VP6lyNKvj8c+6d88qjMoqHFTKl6YS35BwMUQcuq3icC7JNACyEdL/T8etam32h2h+dD1VESCJJ1cp+LEbmRFdFW09IYb1NZNhPhUuPJ3ckGxdN2s72wOwbN3/W7KKmTS0bKK2qeuKTAQp9xFAk8x8l7l6MxIsM/P8aDRwhmxaNQyL5M8jUE+QMRoT+yO9pSNbiras8lPygT+Q+dEmi2lYgcoT+9Fz09+1TbJJ6PVVbWzCqFob5ikv7U6b8ls8hREOV6VXI96lNCJESEAjx8rdSGrYh6jjjXWXQRR5qWf0qEaPWy9uepfRczGS6fnUznHAj+N53YQP/Q7RsxbPpGpDptVx3b+rSuNOipA1aHc7Lf3nfxDjtuDVvUdF32x02UHvEF2yYORrwswRbEGA/pUVJ1QJu5bQJT1GfL+kuhlh44NWjcMNGZkAyrue4VMDalBs4ccd654JqKp303ReoQY8AEJA56qPzn2KE0OE2GbhjShMjYe5JnJBzVdOBY7rDiUFIQL7lTO2n81ehOh068avvwMxN5c3Nxd4wOhSGaGs0ebNYYXrtHrXzDXoeDLp0v/Q=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
    type: Opaque
