---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    token: AgATlLS9GIFjG9lUHPnPbpNDfIrWanH43J+r9TuFdOlkQonFWPSIN+QWnCMboXpZoUiGuF8nVkY9ycWqNEP30xiimNPHkHWqMLxBi98C2pOBQbaGWdhHKvygk8Gjl9Bl/S0+5Hu5LsaGNCsV4KlX2YjFUkA4NO/ZHbHRdeYOlrFz3O0jDF8b4P0fTtVE5qssYITRJMxWzO+8WitsO6/2Ly2pjM/9vwxn87brO3O05fi12iLPIziVUH9/PmA4hxwYCtb03Zx/UeMV4QlespOGMpXWPhdHFREB967ag9qd50Fwfh+J3w+MPmJvmvxy6tRyn7C5wE+NmmFuN0ht1TuNwzHpIyfoVWzjb+SVgTtATCpOPE/TQrYk9buvRAKnlT4hlVgp+513PYu5f6oS0EkFcQU8U5nOw8nBi+JONJr1witlPSGPGSXLIlquXHnXsJS2f+Zi8ivr2e3ehlC0BzFVsLNJMpj2sUEKrybmWSGzFy+DFIG5+zOE8pQzdtBp4+kUBYh8/i9kBKu29/oE9t+Agt66i9prJzSfgQ/5W/67MgANQKi7fqAviZoRzLsdFKE45OLkIaTKRRItCrB0212I24WYvAJSWzOrh2BqtsKJGL7NTWK9MBVwoqlslzxrJ1fOUWX38Fhy6H8s1AL1XMbZlFVfV5S9lxGtZqxYRzmwXBnMmK0weNoawrMri8+/kBL9tJ4=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
    type: Opaque
