---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBC8Ryn994K8zKKXBaGhQgKbmwrGcAjfnScIchHh7313QvjJzU16qg7vlox4LPVu4+UX9i4zDyMvPWqgrB80pSXzAfHG9Wj+dhIBdInG9C1rV7TkdJBqkC49hXsgWVtYLzOuvuup//iXCXJ4jQy8F0oYJ9xqo1D+Smz3OYMuhjfNvg9PC/R8sQ8jxL6zeFjtIgGjDo3wmKruKww+W91/6CtbIwZCuV7u5VjMMnyPbCf9Od4MBT5fUZzXMwwPgJoqZf95SZi1EZe57pfb/WiOdJX/pKjfsx267AIHDKqJTeXiQjpaS1Jtlkee8849zg1VqkYZW4daduiUuFLIVb8CNQDnFTho5qSeuLI2TfpLQFZ8dEeukWnhj/uY14rjo7u2N40IEwWsY6YtaRRwYhO7xR2FEGY/nuyGWZWDRa9x7RU1nRi//Feynj1MW0/VweczNSqnkHa1g1SYrc8cGv+glVd/D1NYSo0svjMRF6BMYwmbHQm1zO9J1NkUFr7ZY7lgGRsSHKB+Pic67g1VYxj1I84CmAOqSdqbHb71Lj66ThBWYuJVW9vLv97MYAukkkclcwyMH03y7b0Va+5Rh2Tks8SP+BqOQuHstatztL79S0gyWcWMLIN6BsFHJ/Qo5Orr0CVyxm7CySBVHLeCjJmzmzR1ZT4MtUeXW88LJrNVQ2rMimw+QdpADYXcqJBAbeC1B7asW0Nf1aDtVEa5Gu/owUeaumubEbo97o7fOVGTjiJ0kDb7bufFrZlGuZAyTPOZ2kFny8sNl5joXmUB3SbE9CtzDswdovIPoqOpfmhwPaMuroJUeO8gKS913tgcJp0W9EgtkwzRRS+vbZvKBLZ13jMSWHyffA/OskUv5xCM9aFwU7+hbibYKn65bMrAQwc8AqR4TK3p6LFwsfTouzL5EOm4R72Ykh+5ouTUVEICtmulDNJO2p/Oec+xr/wCvbfjBRvT1FftVkDg7EoN6IQkGnuFsnX3RORfUWJaIf6P31lLXj29afH36gi64vuh306/io=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
    type: Opaque
