---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBKcSyuIj4RGNlE1h791vDCwsmIu8pLgfGV5xGO2bhq4DGsfGRyPTQIAnn85dRUCe1TmZffbcHVeoqosYKDeZiRjnF7g6smCDwK57zBeeaoLkmyJutSxmkVQfrJDl22/7yW9IJ1xJuEjnYB00l7+b54sCE1Lu3qH/1Y+zNY6ksRf0jZefDka3tnL+tBNLZKSPmtc6/VKImVbAqwspZEd6whVohdwqbSEdb87KMJbz4O0FYlob22n0N+YiBJfzwKpWSlnZtK63kvNp7Bgd0dIZRiSIf0D+EDrJ1+hb/5j2nT8Rqe+smN21NHs3XYP1N50sROJqiih/hFKODXUO4Lod0fr/M8DQjisLCWOlEHQrfYqTHJFUMHo6uNQYD6tTGjIvpAgy4JGqjC97zPdPgNHcwWCUY5Kw+QNrsmastwRBEUo8qFw8ev8hkofTDAOJzbRrqxd4uJfLwby3SDe8dSWqlSbJcI4bU8SW8xaEgPL0xFUeCRW95bwct7OWxQqy7G1ZmYE706Y0TWz+hd8Pyc5kuWipriRW/H1VeMcnzBdRScj52uCJ2t6+pSIPv5ueXkiAoO8aOzj3jWpiUrPTryNzkkh79m7WEH/LcjKhnWMi7Lva36ngKc0bIlr5x5MuHnVCFY9eL2TAWwGczW1qnmqPtED//7xytk36bA0PBxi6rgj2tqsva3g8ckt+sF1vqVkEkX6hbQMtB75sFhoeYDQlx0fgqTcXTOI+AzyTzCh0NGm0Jg4rcH7v4KGDXWOuDl8/YhXzJXM80WBXiPu1en231UBOHC9V66HPwGqd6oZCYO71ysaCN+oxg05CLC4EG4QiWaLtsl5N7p//cbiU+ANQHkHaXvXn9RKMHe8RCKqRyKBbMWQ+/CtdYyyPQaFk4c3lUoxK+ZyR0YR/DupFqFm2K5mKzuY7yMKlL5Lx0buu85Y4/4uwkF9hgi0pwSZnhKj5kYTUUPmssRqgQnC5sWo+O/YJlAbvjNNfCUV89H9bofrXHq9k0vT/LxhjO9jr+W0Uk=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
    type: Opaque
