---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    token: AgAxBI827RYGmj2k/00jt7fv/Ci/Emb332NZa/4XD4m5toekwmZOp1iFuFHufEFMJOmc3+qQuh6gvVPsV/c3XWvoN37pKfg7g2F7XBP65wCAgluwha610IOTeEztsnzCmpkOzfhaF5kTRHrsNeniSFm5mMpjJd8hqPDPvpiVjG8iah2gdjbMLh8jpABRgNm0aSWhhUPST4xS0S0kCDJBxiIBiP7wm1kh7ipJt0XeahW3CT+3SwC2x0pA2kezsh8JdZIRyg47N6KdTnag4LKgELuw9lWzTRbYKLNsStgrXAZtE8PUgDP9uXSu+qRXnY//kubjY7lAF4kzSrq7eCA4DdYknplgMQ+bgrn4BAtvat38KCh0HY6UChjmSxV9Xs+oh0bkWFJt2mc/BNgDv1lhF0X6kBibtCr2p7VxYDBnZCIatKC3TKDbefI0nIIuyEtJ0D77lTedV/FilK9XI6A9qcVkBWgHPNODSzG8CdCbeNoxfHYLIRMJ/pf6AH6zQ/VqXlDB/E3cRX2hcrAhlZ+H0Pej9d/v3F9/2FbrLp/sPuxgjMTmaRAJDBAxBrCsMzy74beHuCnp4XbzvkE1qO28ticRcOjtkADopUjs1oUCgoAwKNXcKlOHB18FNwFTwXBupK4Cr+zEJuh3Hgl1ELPcszU82mjrYZCTXGz2lhRGaZpJ+9uyjIX45syJ7XJ4M0GSiF+SGKx69mqO+zIYv1vGxkiwhDW8bwf7HGO/cXEuQ/J5LybSh9delYqcUyPjg0fEWkDZJZf8oXg8ewe/iV0AabMiuI7m4F7BTMLI/iZVYWrNPEo2GVm8mC+k1qG4KiP1JNM0tRf+3rwNNdgNqMQ0b0NWL+Hdve9kR5sFeLCehHoIX1hJqyY0jdp1duYyqDsTRKzIWyjRpL5ZGPaJQX/hsit7/Aftw3cVFTzG3X2bpxvSjnxwOqq6x4M2
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
    type: Opaque
