---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgBvTJ1/PNEt0NBgFBThoPiIKMOu2HshLs6gvdVLpj8bVICwfmLL3yH5NoMkO6Vv+t/bs2G/x5H5vOBKuB94KGeEXjBIfygF6J0MsPeWO87OXZ+q0ds9zBBipCoRvETABhFjTdar9qi0RQhRAF9X5eLBA+h6q9KioWTtbC0mBXgC7Wc40e4/FLtIvRCEO1S3D6zs42HYKrRiOaJar5+nsvkHJwWlTcF84uzWeEjpgcIv1dp7Nm1Gf6YhR//8Zi89helVtI1/FVqBUAu5oMqmzKhlAjcrU9pyiW7Z1VRKbOceYk5hdLPFJLEw0bJtV28cY4jX1ggPxxvIoPuaNsZPNbS8ZyOx24gMuvmScYTXknQNFJJbWDHOVDvyg6s2V0lC3/Qk/xGHi8ggEzXnJvrHuj97muGgbTTUsfR6yzlMZ2bivTV6vhoEoYfHnfxYVL/l8hpzjgU1mpw2tL3Lckd3NGhAZDgw1Lp39LsOdY9EbgBJxbX++rYDB6MxtJNx458m/jNq+VI4J4pOWLqy8LCQozshbmypQRHw8hWdlU8OTPADTXVnkXAZ2MrgGjO8CnaHj+1OX2H6dvGipgotuok6O3DU/0FrU6w+45wMvVUIzhWGXMxF01yBp/BKgCzvT9jEtxYgWdrXWh9tnX+E8wFcoG4EVf8otYByQ2k2AqjmfYXljRUXQ3x1aEQJjei6qVATuducqTqwNS1vyRa/hU7kv6+BIgG5qGXw9pyoCutP1vgESw==
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-admin-token
      namespace: vaultwarden
    type: Opaque
