---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-smtp
  namespace: vaultwarden
spec:
  encryptedData:
    SMTP_PASSWORD: AgAFkxGdGMy20WbDuuOc6iH4ySPoJHKeOJVPzpP9f0RNvofZkP3jPNUTssh8AlJMh3u/uLHh4qGc5GDsTN5jCMj8PI9VzGGItgvioaSD7aFGSVho/EmvA1g43hHZUuBoTkX3VFLyFnn3sMDSIzKq0OcMo7hhK/m6M2KHC2Na395svrrD1ZHOOA5kBeQr85HXeWO1yE3oU3zptnkrpstWLGKa0cWVUbqAR8IU6YSW32KHEBneJpYGCFO2Jb49tfnE3iYWhCuoqu5QCNa1BUWmYHGaCad0BwxVzYIEMmK7KNaRTpDswisLUXhTm/V9ncY0j31ih/XZx64fI9iPwtKbZ0MdclWpj5TFCMWI4r5XN2P6na+6X8IvQBnN4pYpj9LUAq9q1ZG6j/Q5ADX2h/p1AhSZcLSDurgpDQ2aV+b1v/UvBhtM2npDy2ut9XrYGsxc4gSh7R7HPO1SvdmBPrT20lMLaVP71RQkiEH8KJ9TSQ3BBde36eZEO8fR4SwI02+0JZsjApwCoQ+5RAYTKC63zF0+vkYLJ7Vj1ZE4xY2+3JhBIdbKbvTZ8WMhGwqg4BCj0WdKdlYt5YMXNgjS6+3UkARXNVgOSqQy4TROTXh7X2VTjC5tgDs38YLXXRxeNmDHPnxZm/is4r6PggDPU9V7baHmDS6zSIcST7q7McLRZSYBIGNl54FyyqSwJCvJA8eoiAb+Vn70uidhIuQMDcKYI997
    SMTP_USERNAME: AgARhjKhOIF2Hk/XA5jZwcioZhx2PP+7QLRS9/4/8TKdbBLCc4mq2NWvTjRHKztMNdZeviKTheqawmh0QXVVkHxs1tuNJabIakEYGW6lwjqnkeLP5zoz89gwlcdrjUW1QcuJznZvzEL67Ln2EyX/n9nIF4pkoxqG/VAgJpkID/8D8+9wjZNiVQzp9fA4zfCTB9lCxIbSedevc7oYlclTC+4i0lupX5U4t69eJKlIn3FaY4tlFmhWusBC8HDcBdLD0lkaPSPN0YEcTHVZjrN7aK2CbcCWxoHCd+tAjfLNy6Jrl/vX6wjPIombgmhi7J9zExAvDP1vb5fMipuXrJexjj4Y0m5I9DpZV/ZumKl1op8pREwmVNTtGAWyQz9Z0qBQePEX9utEW7KKTZN7F+jl2DfUL+Ugp1G9sXyesTNqZ62qa8QDn6L2xkmkhoROMZUCCgjIwXVzGjJuwhNrv0EWDYy6C3XPyw/c045SxVsuCXhh7noB9iif20QAOgVCo+mAeBJIwcQLAmQHxr9mWXhGO0wsV9wT+WkIAZspvwpM/TxtlQofnOJWrEPtdVH4j0ZWiOonOYelGyUnYOPJUVRcjyLri49e7rHKkDXAFOjYnZbg1X4/xQyUZUSUlP3a9KDPk8jH99bQHkyY3k92Pj0O/koBsaatnZIhdsy2904EPGY1hockDdpb0e3bmJd5agsaAH3Ai6ILyycvGdikSW5q7L66mA6t/w==
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-smtp
      namespace: vaultwarden
    type: Opaque
