---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-smtp
  namespace: vaultwarden
spec:
  encryptedData:
    SMTP_PASSWORD: AgCu3aW7XrdDUCBxAJp0MxtdXQicpJn+OuTJvhj0HCr2vj7lAccJklAvot927Z/9gDf5vce9x84XZCYPwBZsXfiA8ypXZZYNsjvTKoh9mLsNBvzTRnjwOjR5nIni4maPdgLnqTGHAC6FGYXXYjsN5d1gpButohJ9Lgtv3pW1AqEiuS10SrDksw7DNdleG6Xl4V4Qsgtt0jkL9m97WK4IHeNtAati588gdiNaH9CPwaKfkFHgkGKyu2LYSKCXAZ/emuQwV5YY2atJ1WVr2lJJXsyyPah1q9BzPI6QjcrK2zsA//Dtyodvl+kvdHnKtntvCvefmBIwm0reFNES9f6x2FhFKrVja9CzAgl3+rFXr9pS+MBp72fgEDKESmKQT3s639HZBrO331gTxC8nyW3iyMArdV+PPtSsDTxN+ysw1HKnV3gF1rMduaUz6IIac7oizUMf07aPavUVqrdEU82zepj3cQ0sVLeEKOMHJutHfVm9I7XbygpMA/gNoirzRxv2TzeB1tL3cFskk84McQ0eWBol7LcUc7hsqgi53PNAh4G3eLxp+mXWb08yLl3atn3P36+tCfuJT80z+VfGij31tkSWNCDe8YyLt5+wOA3tNNMNTfgUkev7cX0lDoaJ1JZLWsiYGnWjizNOs/dSQv3HyVV1uOFsWzzSobtkHnlG2KD6YqDuojF3CGczDv1kRHlGLpXPvxuDYUZbKGScVaZuZuiI
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-smtp
      namespace: vaultwarden
    type: Opaque
