---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: neo4j-auth
  namespace: neo4j
spec:
  encryptedData:
    NEO4J_AUTH: AgAI5un7Gsf/Fb1rwF+PJ6VRu6o5hFN7Axo4yRhT399yB4n913H1Jqz1kFY5fshr66QdIp9BWo7Bv+9VXyeUtRmCOxoP/JyXtsB+x93ck4NBKTVFco4q3O9ta6eNlj2v1GI28z/+ujdr6ZC0Rii/fkVxyqR5xBqAaAsLBkuedB2tbF5ALlL1hG9TdB07CdfV0Zv61ZXqQa9VGg4j0BjUZgd6kLuOakNdz1+NJli9cIosibQ+ews9nnwo4rPgu5yvue8Zi3I3dlhHZoYhR4118mqIj5CAzSyN8syNrJsDv4VZ7JLGlI+QnUsmavTfASs/DhN0L+jAkct6eMmrdzEgMNd4Q1F7c6La48UjUWdUjcazHuOgpr6PbwYLmaEI5v/xg2qzlLxkP2HsMUKGOy0GqoknbE+YNle/ZQveMfMPCTw8XgxYFCnXq9k6Rzn7u7BH9Jc/HJMiwUz3Q5J21tw8q5GCogNsUE026XwXKqGvCyyW+X8imJbH/SKFQbcAIgK5We0LHifoZcaBde/Q7031awjRk1fCLYXqyJggW9AXuxErsbfBq9Xm1jcbTk0thx8Tsg88trw8QEqWFtWSg5yiu1XGFbnEiCfAkrwxG730k4F+PE1b/qC5t6BQhAGQBDMNSTsvxqVwNDoO7SCo6UvZFFrFl3fl06n1I6gvfnTYg7mhCMZQ6FKaOGQmWZj3sJzFUklM0z8+6VjU1uL4tLphVJ2fwXeAyDs1hCehYBIy5tFqpPyOjgvBVQ==
  template:
    metadata:
      creationTimestamp: null
      name: neo4j-auth
      namespace: neo4j
    type: Opaque
