apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cv-datastar
  namespace: cv-datastar
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`cv.watchtoken.org`)
      services:
        - name: cv-datastar
          port: 8080
