apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - ingressroute.yaml
  - ingressroute-alacaba.yaml
  - ingressroute-apex.yaml
  - ingressroute-https.yaml
  - certificate-alacaba.yaml
  - middlewares
