apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: it-tools
  namespace: it-tools
spec:
  interval: 1h
  chart:
    spec:
      chart: it-tools
      version: "0.2.x"
      sourceRef:
        kind: HelmRepository
        name: jeffresc
        namespace: flux-system
  values:
    image:
      repository: corentinth/it-tools
      tag: latest
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: it-tools.local
          paths:
            - path: /
              pathType: Prefix
              port: 8080
