---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-pdf-unlocker-values
  namespace: pdf-unlocker
spec:
  encryptedData:
    values.yaml: AgBfIo82bRRKSsi7mtoXI8jHOjCkzesqZMZbZFatVyULVBbLkEoFyqs/y9PLk/GVz9HW9vFe2PhadpOtw1YSgMu2YNjGkU5ObQQLrZCPHY7Sow1PBdbZ0gJH9jxNF8TuFT7UyS37lHWYH7446Je+sv4GKD/MoGEbULiDo9HJkZ4ZiRxUicdHsijAUjM488rVXxuVSEx6/971ZhAo9ol6YAQEaY0oVkbS6OOOdYSPOszemAZvByDDzjJH5eRebG8qoaQyBD4GWfSsLi4uqBtxCkLrmFeU82gD7LSkjl/srkv6qmzS8Pj9ycsI5Z9MLer6hDHxioJAByK2YsFmYZT3Vfy9fD0yDrh6CjKZWtJorx5n2FnijefVVJ3LdEjZ001bJXzywfFjNMr1IQl5LeijpNM6z/s0fSMV9pEzhGirkW1GtobOufxXn0AryLpfREDCot9ONtwPPw3+uEiTibpgnkyHTtKrkoV1PNmCxsxo+J3VOTn+P++LnXVc2ozAWIr+uIL8TkpjUMk7HZvrJQKXMl90zrgwtzjQmUbTeimdabGdV1m/ZfgUXYPu+8QFtx1OEU5rgHxMIyax2OiEblBdQq9IPXGiHnqp/bI7PinCNE+mvGPN9voD7vIakMSQyXk5oZb/fIEm1wsjx8KnHtpWHGLM3MMSjciOkxDy38m1PMNvoFP6u1tTiXImk28RRS3Yv4M6iMCbtKMqrYzyYtFECAWKRZC5sNmzwygoUkNKkEYeRfjaVoQptYDEmO+2UwVP781bNJhVpf68Yg7U9JOFg7G/r/H0fvctD2OGFQdNY4VfbghgSYfCAaEG0y7LQjCDO0lOYrshmrhRp9hBGmijrft+9b6+
  template:
    metadata:
      creationTimestamp: null
      name: paperless-pdf-unlocker-values
      namespace: pdf-unlocker
    type: Opaque
