---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-pdf-unlocker-values
  namespace: pdf-unlocker
spec:
  encryptedData:
    values.yaml: AgCouPa6A4tuPcPNFP//aHD/D5bK4Iecp8gAj6DA3PkMR6nKJD+DlwQmlN36y1NFccV83UFUtofrTO6OigPx1hFgOXI5SkehMLR2dW2x/IP8g1CBPR0IJOrI6r+iXQkB3MhjVdFIRSxVaSdkVj4ukRyBfW5fm0r3+yUtyBLIrU/1gIJfCyDnGn8T+MAPH/GaGrFcVvSJzqD6U87gi4Ni3kOw4crsQqD+SbELO77SHi7POGdnenjyTixqLOWorqHgKuVMkSJ0yS24EJwtymw0VC6j4lvtPQCN/FfYgq2wu/nzqjw+JQk43dHBN8u88muGPi2UZcof8tkhV+grtotTzi4SO+9PU2pPj1d5xNyMtcQnnhOiVBNxPzTMkvrMse0TYq8rAk2hFWaMSQO0QHXgFy5jgQR+0tBuEvR5bRk5/Uog5YOtvfkEFWLutgoDIZ21JTr9Vb7r/xMByzX2J8R5+Ddea+vNyCC5yWSXAa7HulK8jWknHRrqryU77Z7hP5/+17mUiGiKHiKB2VM7dn1Yalry45r48WiM3QQhBlgFuluVkN0/kbqpl/Nyp2JnIGdSWG/B/DRqbyYemEZkXYVjBMSvruCDh5tPZcDHk4yBvbXD0OjptCmGm7pkVA5geI4jviX1OLRQU4zLNS/YsADoL4zutuZaxAk87YmqzBbUcEOl/deIAvIRaKYhcrffWM2lSyc=
  template:
    metadata:
      creationTimestamp: null
      name: paperless-pdf-unlocker-values
      namespace: pdf-unlocker
    type: Opaque
